import type { TranscriptSnapshot } from "../core/types";
import { formatClock } from "../core/time";

const STYLE = `
  :host { all:initial; }
  .backdrop { position:fixed; inset:0; z-index:2147483647; display:grid; place-items:center;
    padding:20px; background:#07090db8; backdrop-filter:blur(10px); font:14px/1.45 system-ui,sans-serif; }
  .panel { width:min(580px,100%); border:1px solid #323b4b; border-radius:20px; color:#edf2f8;
    background:#111318; box-shadow:0 28px 90px #000c; overflow:hidden; }
  header { display:flex; justify-content:space-between; gap:20px; padding:22px 24px; border-bottom:1px solid #262d39; }
  .eyebrow { color:#8ab4f8; font-size:11px; font-weight:800; letter-spacing:.15em; text-transform:uppercase; }
  h2 { margin:5px 0 0; font-size:20px; line-height:1.25; overflow-wrap:anywhere; } p { margin:7px 0 0; color:#919aab; }
  .close { border:0; color:#aeb7c5; background:transparent; cursor:pointer; font-size:22px; }
  .status { padding:15px 24px; border-bottom:1px solid #262d39; color:#bec7d5; background:#151922; }
  .warning { color:#f4c57a; }
  .preview { display:grid; gap:7px; max-height:156px; padding:14px 24px; overflow:auto; border-bottom:1px solid #262d39; }
  .line { display:grid; grid-template-columns:64px 1fr; gap:10px; color:#b7c0ce; font-size:12px; }
  .line b { color:#8ab4f8; font-size:10px; letter-spacing:.04em; }
  .line span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
  .grid { display:grid; grid-template-columns:1fr 1fr 1fr; gap:10px; padding:20px 24px 24px; }
  .action { min-height:74px; padding:13px; border:1px solid #303949; border-radius:12px; color:#e8edf5;
    background:#171b23; text-align:left; cursor:pointer; }
  .action:hover { border-color:#6684b7; background:#1b2330; }
  .action strong,.action span { display:block; }.action span { margin-top:5px;color:#8993a3;font-size:11px; }
  .action.primary { border-color:#5978a9; background:#182538; }
  @media(max-width:540px){.grid{grid-template-columns:1fr 1fr}}
`;

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;"
}[character]!));

export type OverlayAction = "markdown" | "plain" | "srt" | "vtt" | "copy" | "archive";

interface ActionButton {
  action: OverlayAction;
  label: string;
  hint: string;
  primary?: boolean;
}

const BUTTONS: ActionButton[] = [
  { action: "markdown", label: "Download Markdown", hint: "Chapter-aware, portable transcript.", primary: true },
  { action: "plain", label: "Download Plain Text", hint: "Clean prose, ready to paste into an LLM." },
  { action: "copy", label: "Copy Transcript", hint: "Put clean prose on the clipboard." },
  { action: "srt", label: "Download .srt", hint: "Timed subtitle file." },
  { action: "vtt", label: "Download .vtt", hint: "WebVTT subtitle file." },
  { action: "archive", label: "Save to Archive", hint: "Store locally for search and retrieval." }
];

export function showOverlay(snapshot: TranscriptSnapshot | null, onAction: (action: OverlayAction) => void): void {
  document.querySelector("[data-tube-overlay]")?.remove();
  const host = document.createElement("div");
  host.dataset.tubeOverlay = "";
  const shadow = host.attachShadow({ mode: "open" });
  const warning = snapshot?.warnings[0];
  shadow.innerHTML = `<style>${STYLE}</style><div class="backdrop"><section class="panel" role="dialog" aria-modal="true">
    <header><div><div class="eyebrow">YOUTUBE TRANSCRIPT</div><h2></h2>
      <p></p></div>
      <button class="close" aria-label="Close">×</button></header>
    <div class="status ${warning ? "warning" : ""}"></div>
    ${snapshot?.segments.length ? `<div class="preview">${snapshot.segments.slice(0, 6).map((segment) =>
      `<div class="line"><b></b><span></span></div>`).join("")}</div>` : ""}
    <div class="grid">
      ${BUTTONS.map((button) => `<button class="action ${button.primary ? "primary" : ""}" data-action="${button.action}"><strong>${button.label}</strong><span>${button.hint}</span></button>`).join("")}
    </div></section></div>`;
  shadow.querySelector("h2")!.textContent = snapshot?.title || "No transcript detected yet.";
  shadow.querySelector("header p")!.textContent = snapshot
    ? `${snapshot.author} · ${snapshot.segments.length} segments${snapshot.chapters.length ? ` · ${snapshot.chapters.length} chapters` : ""}`
    : "Open a YouTube watch page with captions to capture a transcript.";
  shadow.querySelector(".status")!.textContent = warning
    ? warning
    : (snapshot
        ? `Transcript ready${snapshot.captionLanguage ? ` · ${snapshot.captionLanguage}${snapshot.captionAutoGenerated ? " (auto-generated)" : ""}` : ""}.`
        : "No transcript captured on this page.");
  shadow.querySelectorAll(".line").forEach((row, index) => {
    const segment = snapshot?.segments[index];
    if (!segment) return;
    row.querySelector("b")!.textContent = formatClock(segment.startMs);
    row.querySelector("span")!.textContent = segment.text;
  });
  shadow.querySelector(".close")?.addEventListener("click", () => host.remove());
  const backdrop = shadow.querySelector(".backdrop");
  backdrop?.addEventListener("click", (event) => {
    if (event.target === backdrop) host.remove();
  });
  shadow.querySelectorAll<HTMLElement>("[data-action]").forEach((button) =>
    button.addEventListener("click", () => {
      onAction(button.dataset.action as OverlayAction);
      host.remove();
    })
  );
  document.documentElement.append(host);
}
