import type { ArchiveListItem, TranscriptSnapshot } from "./types";

const DB_NAME = "tube-utilities";
const STORE = "transcripts";
const DB_VERSION = 1;

function openDatabase(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = () => {
      const database = request.result;
      const store = database.createObjectStore(STORE, { keyPath: "id" });
      store.createIndex("capturedAt", "capturedAt");
      store.createIndex("videoId", "videoId");
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function storeRequest<T>(
  mode: IDBTransactionMode,
  operation: (store: IDBObjectStore) => IDBRequest<T>
): Promise<T> {
  const database = await openDatabase();
  return new Promise((resolve, reject) => {
    const transaction = database.transaction(STORE, mode);
    const request = operation(transaction.objectStore(STORE));
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
    transaction.oncomplete = () => database.close();
  });
}

export async function saveSnapshot(snapshot: TranscriptSnapshot): Promise<string> {
  const id = snapshot.id || crypto.randomUUID();
  await storeRequest("readwrite", (store) => store.put({ ...snapshot, id }));
  return id;
}

export async function getSnapshot(id: string): Promise<TranscriptSnapshot | undefined> {
  return storeRequest("readonly", (store) => store.get(id));
}

export async function deleteSnapshot(id: string): Promise<void> {
  await storeRequest("readwrite", (store) => store.delete(id));
}

export async function listSnapshots(query = ""): Promise<ArchiveListItem[]> {
  const records = await storeRequest<TranscriptSnapshot[]>(
    "readonly",
    (store) => store.getAll()
  );
  const normalizedQuery = query.trim().toLowerCase();
  return records
    .filter((record) =>
      !normalizedQuery ||
      record.title.toLowerCase().includes(normalizedQuery) ||
      record.author.toLowerCase().includes(normalizedQuery) ||
      record.videoId.toLowerCase().includes(normalizedQuery) ||
      record.renderedMarkdown.toLowerCase().includes(normalizedQuery)
    )
    .sort((a, b) => b.capturedAt.localeCompare(a.capturedAt))
    .map(({ id, videoId, title, author, capturedAt, captionAutoGenerated, completeness }) => ({
      id: id!,
      videoId,
      title,
      author,
      capturedAt,
      captionAutoGenerated,
      completeness
    }));
}
