import type { Chapter, TranscriptDraft, TranscriptSegment, TranscriptSnapshot } from "./types";
import { formatClock, formatSrtTime, formatVttTime } from "./time";

const yamlValue = (value: string) => JSON.stringify(value);
const formatDuration = (seconds: number): string => {
  const rounded = Math.max(0, Math.round(seconds));
  const hours = Math.floor(rounded / 3600);
  const minutes = Math.floor((rounded % 3600) / 60);
  const remainder = rounded % 60;
  return hours > 0
    ? `${hours}h ${minutes}m ${remainder}s`
    : `${minutes}m ${remainder}s`;
};

const collapseWhitespace = (value: string): string => value.replace(/\s+/g, " ").trim();

/** Chapter boundary lookup: returns the index of the chapter a segment falls into. */
function chapterIndexFor(chapters: Chapter[], startMs: number): number {
  let index = 0;
  for (let i = 0; i < chapters.length; i += 1) {
    if (chapters[i]!.startMs <= startMs) index = i;
    else break;
  }
  return index;
}

/**
 * Markdown export with YAML front matter. When the video defines chapters,
 * the body is segmented under `## H:MM:SS Title` headings; otherwise the
 * transcript renders as a single block. Inline `[M:SS]` timestamps are
 * included by default so the export stays navigable.
 */
export function toMarkdown(draft: TranscriptDraft, options: { includeTimestamps?: boolean } = {}): string {
  const { includeTimestamps = true } = options;
  const { video } = draft;
  const lines: string[] = [
    "---",
    `title: ${yamlValue(video.title)}`,
    `author: ${yamlValue(video.author)}`,
    `source: ${yamlValue(video.sourceUrl)}`,
    `video_id: ${yamlValue(video.videoId)}`,
    `duration: ${formatDuration(video.lengthSeconds)}`,
    `captured_at: ${new Date().toISOString()}`,
    `captions: ${yamlValue(draft.captionTrack?.languageCode || "unknown")}`,
    `auto_generated: ${draft.captionTrack?.isAutoGenerated ? "true" : "false"}`,
    `completeness: ${draft.completeness}`,
    "---",
    "",
    `# ${video.title}`,
    ""
  ];
  const segments = draft.segments;
  if (!segments.length) {
    lines.push("_No transcript segments were captured._", "");
  } else if (draft.chapters.length) {
    const chapters = draft.chapters;
    let cursor = 0;
    for (let c = 0; c < chapters.length; c += 1) {
      const chapter = chapters[c]!;
      const nextStart = chapters[c + 1]?.startMs ?? Infinity;
      lines.push(`## ${formatClock(chapter.startMs)} ${chapter.title}`, "");
      while (cursor < segments.length && segments[cursor]!.startMs < nextStart) {
        const segment = segments[cursor]!;
        lines.push(formatSegmentLine(segment, includeTimestamps));
        cursor += 1;
      }
      lines.push("");
    }
  } else {
    for (const segment of segments) {
      lines.push(formatSegmentLine(segment, includeTimestamps));
    }
    lines.push("");
  }
  if (draft.warnings.length) {
    lines.push("## Capture warnings", "", ...draft.warnings.map((warning) => `- ${warning}`), "");
  }
  return lines.join("\n");
}

function formatSegmentLine(segment: TranscriptSegment, includeTimestamps: boolean): string {
  const text = collapseWhitespace(segment.text);
  if (!text) return "";
  return includeTimestamps ? `[${formatClock(segment.startMs)}] ${text}` : text;
}

/** Plain prose: timestamps stripped, segments joined with spaces, paragraph breaks at long pauses. */
export function toPlainText(draft: TranscriptDraft): string {
  const paragraphs: string[] = [];
  let current: string[] = [];
  let lastEnd = -1;
  const PARAGRAPH_GAP_MS = 2_000;
  for (const segment of draft.segments) {
    const text = collapseWhitespace(segment.text);
    if (!text) continue;
    if (lastEnd >= 0 && segment.startMs - lastEnd >= PARAGRAPH_GAP_MS && current.length) {
      paragraphs.push(current.join(" "));
      current = [];
    }
    current.push(text);
    lastEnd = segment.endMs;
  }
  if (current.length) paragraphs.push(current.join(" "));
  return paragraphs.join("\n\n");
}

/** SubRip (.srt) subtitle format. */
export function toSrt(draft: TranscriptDraft): string {
  const blocks: string[] = [];
  draft.segments.forEach((segment, index) => {
    const text = collapseWhitespace(segment.text);
    if (!text) return;
    blocks.push(
      `${index + 1}`,
      `${formatSrtTime(segment.startMs)} --> ${formatSrtTime(segment.endMs)}`,
      text,
      ""
    );
  });
  return blocks.join("\n");
}

/** WebVTT (.vtt) subtitle format. */
export function toVtt(draft: TranscriptDraft): string {
  const blocks: string[] = ["WEBVTT", ""];
  draft.segments.forEach((segment) => {
    const text = collapseWhitespace(segment.text);
    if (!text) return;
    blocks.push(
      `${formatVttTime(segment.startMs)} --> ${formatVttTime(segment.endMs)}`,
      text,
      ""
    );
  });
  return blocks.join("\n");
}

/** The most reusable clipboard export: clean prose, no timestamps. */
export function toCopyText(draft: TranscriptDraft): string {
  return toPlainText(draft);
}

/**
 * Freezes a captured draft into an immutable snapshot, pre-rendering every
 * export format once so the archive viewer and re-exports are instant.
 */
export function normalizeSnapshot(draft: TranscriptDraft, capturedAt = new Date().toISOString()): TranscriptSnapshot {
  const { video, captionTrack } = draft;
  return {
    schemaVersion: 1,
    videoId: video.videoId,
    title: video.title,
    author: video.author,
    sourceUrl: video.sourceUrl,
    capturedAt,
    lengthSeconds: video.lengthSeconds,
    captionLanguage: captionTrack?.languageCode,
    captionAutoGenerated: captionTrack?.isAutoGenerated,
    chapters: draft.chapters,
    segments: draft.segments,
    renderedMarkdown: toMarkdown(draft),
    plainText: toPlainText(draft),
    srt: toSrt(draft),
    vtt: toVtt(draft),
    completeness: draft.completeness,
    warnings: draft.warnings
  };
}
