import type { CaptionTrack, TranscriptDraft, TranscriptSegment, VideoMeta } from "./types";
import { parseChapters } from "./chapters";

/**
 * Transcript capture pipeline.
 *
 * Rather than scraping YouTube's "Show transcript" panel (brittle shadow DOM
 * that the user must open first), we read the same caption data the player
 * itself uses. Each watch page embeds `ytInitialPlayerResponse`, which exposes
 * `captions.playerCaptionsTracklistRenderer.captionTracks[]` — a list of
 * timed-text track URLs. Fetching a track with `&fmt=json3` returns YouTube's
 * structured JSON event format, which parses cleanly into timed segments.
 *
 * Everything runs inside the content script on the already-granted
 * youtube.com origin, so the caption-track fetch is same-origin and needs no
 * extra permissions or third-party services.
 */

export interface CaptureOptions {
  /** Preferred caption language code (e.g. "en"). Falls back to defaults when absent. */
  preferredLanguage?: string;
}

export interface CaptureResult {
  draft: TranscriptDraft;
}

type FetchText = (url: string, init?: RequestInit) => Promise<string>;

export class TranscriptionError extends Error {
  constructor(message: string, readonly recoverable = false) {
    super(message);
    this.name = "TranscriptionError";
  }
}

interface PlayerResponseCaptionTracks {
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string; runs?: { text?: string }[] };
  baseUrl?: string;
  vssId?: string;
}

interface PlayerResponseCaptions {
  playerCaptionsTracklistRenderer?: { captionTracks?: PlayerResponseCaptionTracks[] };
}

interface PlayerResponseVideoDetails {
  videoId?: string;
  title?: string;
  author?: string;
  lengthSeconds?: string;
  shortDescription?: string;
}

interface PlayerResponsePlayability {
  status?: string;
  reason?: string;
}

interface PlayerResponse {
  captions?: PlayerResponseCaptions;
  videoDetails?: PlayerResponseVideoDetails;
  playabilityStatus?: PlayerResponsePlayability;
}

function readInnertubeApiKey(html: string): string | undefined {
  return html.match(/"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"/)?.[1]
    || html.match(/"innertubeApiKey"\s*:\s*"([^"]+)"/)?.[1];
}

/** Extracts and parses the embedded `ytInitialPlayerResponse` object from the page HTML. */
export function readPlayerResponse(html: string): PlayerResponse | null {
  const marker = "ytInitialPlayerResponse";
  const start = html.indexOf(marker);
  if (start === -1) return null;
  const braceStart = html.indexOf("{", start);
  if (braceStart === -1) return null;
  let depth = 0;
  let inString = false;
  let escape = false;
  for (let i = braceStart; i < html.length; i += 1) {
    const character = html[i]!;
    if (inString) {
      if (escape) escape = false;
      else if (character === "\\") escape = true;
      else if (character === '"') inString = false;
      continue;
    }
    if (character === '"') inString = true;
    else if (character === "{") depth += 1;
    else if (character === "}") {
      depth -= 1;
      if (depth === 0) {
        const slice = html.slice(braceStart, i + 1);
        try {
          return JSON.parse(slice) as PlayerResponse;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function readTrackName(raw: PlayerResponseCaptionTracks): string {
  const simple = raw.name?.simpleText;
  if (simple) return simple;
  const runs = raw.name?.runs;
  if (runs?.length) return runs.map((run) => run.text || "").join("").trim();
  return raw.languageCode || "Unknown track";
}

/** Normalizes YouTube's caption-track descriptors into the extension's `CaptionTrack` type. */
export function normalizeCaptionTracks(raw: PlayerResponseCaptionTracks[] | undefined): CaptionTrack[] {
  if (!raw?.length) return [];
  return raw.map((track) => ({
    languageCode: track.languageCode || "und",
    kind: track.kind,
    name: readTrackName(track),
    baseUrl: track.baseUrl || "",
    vssId: track.vssId,
    isAutoGenerated: track.kind === "asr" || track.vssId?.startsWith("a.") === true
  })).filter((track) => track.baseUrl);
}

/**
 * Picks the best caption track for the user. Priority:
 * 1. A manual (non-ASR) track in the preferred language.
 * 2. Any manual track (when the preferred language is missing).
 * 3. An ASR track in the preferred language.
 * 4. The first available track (usually the default ASR track).
 */
export function chooseTrack(tracks: CaptionTrack[], preferredLanguage?: string): CaptionTrack | undefined {
  if (!tracks.length) return undefined;
  const manual = tracks.filter((track) => !track.isAutoGenerated);
  const auto = tracks.filter((track) => track.isAutoGenerated);
  if (preferredLanguage) {
    const byPref = (track: CaptionTrack) => track.languageCode.toLowerCase() === preferredLanguage.toLowerCase();
    const manualPref = manual.find(byPref);
    if (manualPref) return manualPref;
    const autoPref = auto.find(byPref);
    if (autoPref) return autoPref;
  }
  return manual[0] ?? auto[0] ?? tracks[0];
}

function orderedTracks(tracks: CaptionTrack[], preferredLanguage?: string): CaptionTrack[] {
  const chosen = chooseTrack(tracks, preferredLanguage);
  const preferred = preferredLanguage?.toLowerCase();
  return [...tracks]
    .sort((a, b) => {
      const score = (track: CaptionTrack): number => {
        let value = 0;
        if (chosen && track.baseUrl === chosen.baseUrl) value += 100;
        if (preferred && track.languageCode.toLowerCase() === preferred) value += 40;
        if (!track.isAutoGenerated) value += 20;
        if (track.languageCode.toLowerCase().startsWith("en")) value += 5;
        return value;
      };
      return score(b) - score(a);
    });
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: { utf8?: string }[];
}

interface Json3Payload {
  events?: Json3Event[];
}

const decodeHtmlEntities = (value: string): string => {
  if (!value.includes("&")) return value;
  return value
    .replace(/&#(\d+);/g, (_match, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_match, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
};

const collapseWhitespace = (value: string): string => value.replace(/\s+/g, " ").trim();

/** Maps YouTube JSON3 caption events to normalized transcript segments. */
export function parseJson3Events(payload: Json3Payload): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  for (const event of payload.events || []) {
    if (event.tStartMs === undefined) continue;
    const text = (event.segs || []).map((segment) => decodeHtmlEntities(segment.utf8 || "")).join("");
    const cleaned = collapseWhitespace(text.replace(/\n/g, " "));
    if (!cleaned) continue;
    const duration = event.dDurationMs && event.dDurationMs > 0 ? event.dDurationMs : 0;
    segments.push({
      startMs: event.tStartMs,
      endMs: event.tStartMs + duration,
      text: cleaned
    });
  }
  return segments;
}

export function parseTimedTextXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const pattern = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(xml))) {
    const attributes = match[1] || "";
    const rawText = match[2] || "";
    const start = attributes.match(/\bstart="([^"]+)"/)?.[1];
    const duration = attributes.match(/\bdur="([^"]+)"/)?.[1];
    if (start === undefined) continue;
    const startMs = Math.round(Number(start) * 1000);
    const durationMs = duration === undefined ? 0 : Math.round(Number(duration) * 1000);
    if (!Number.isFinite(startMs)) continue;
    const text = collapseWhitespace(decodeHtmlEntities(rawText.replace(/<[^>]+>/g, " ")));
    if (!text) continue;
    segments.push({
      startMs,
      endMs: startMs + (Number.isFinite(durationMs) ? durationMs : 0),
      text
    });
  }
  return segments;
}

function withCaptionFormat(baseUrl: string, format?: string): string {
  try {
    const url = new URL(baseUrl);
    if (format) url.searchParams.set("fmt", format);
    else url.searchParams.delete("fmt");
    return url.toString();
  } catch {
    if (!format) return baseUrl.replace(/([?&])fmt=[^&]*&?/, "$1").replace(/[?&]$/, "");
    const withoutFormat = baseUrl.replace(/([?&])fmt=[^&]*&?/, "$1").replace(/[?&]$/, "");
    const separator = withoutFormat.includes("?") ? "&" : "?";
    return `${withoutFormat}${separator}fmt=${encodeURIComponent(format)}`;
  }
}

async function loadCaptionSegments(
  track: CaptionTrack,
  fetchImpl: FetchText
): Promise<TranscriptSegment[]> {
  const attempts = [
    { format: "json3", parser: (body: string) => parseJson3Events(JSON.parse(body) as Json3Payload) },
    { format: undefined, parser: parseTimedTextXml },
    { format: "srv3", parser: parseTimedTextXml }
  ];

  const errors: string[] = [];
  for (const attempt of attempts) {
    const url = withCaptionFormat(track.baseUrl, attempt.format);
    try {
      const body = await fetchImpl(url);
      if (!body.trim()) throw new Error("Caption response was empty.");
      const segments = attempt.parser(body);
      if (segments.length) return segments;
      errors.push(`${attempt.format || "default"} returned no transcript segments`);
    } catch (error) {
      errors.push(`${attempt.format || "default"}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  throw new Error(errors.join("; "));
}

function buildVideoMeta(response: PlayerResponse, sourceUrl: string): VideoMeta {
  const details = response.videoDetails || {};
  const url = (() => { try { return new URL(sourceUrl); } catch { return null; } })();
  const videoId = details.videoId || url?.searchParams.get("v") || "";
  const lengthSeconds = Number(details.lengthSeconds) || 0;
  return {
    videoId,
    title: details.title || "Untitled video",
    author: details.author || "Unknown channel",
    lengthSeconds: Number.isFinite(lengthSeconds) ? lengthSeconds : 0,
    shortDescription: details.shortDescription || "",
    sourceUrl
  };
}

function currentSourceUrl(): string {
  return typeof location !== "undefined" ? location.href : "";
}

async function resolvePlayerResponse(
  source: string | Document,
  fetchImpl: FetchText
): Promise<{
  response: PlayerResponse | null;
  sourceUrl: string;
  apiKey?: string;
  usedNetworkFallback: boolean;
}> {
  const sourceUrl = currentSourceUrl();
  const html = typeof source === "string" ? source : source.documentElement.outerHTML;
  const response = readPlayerResponse(html);
  if (response || typeof source === "string" || !sourceUrl) {
    return { response, sourceUrl, apiKey: readInnertubeApiKey(html), usedNetworkFallback: false };
  }

  try {
    const freshHtml = await fetchImpl(sourceUrl);
    return {
      response: readPlayerResponse(freshHtml),
      sourceUrl,
      apiKey: readInnertubeApiKey(freshHtml),
      usedNetworkFallback: true
    };
  } catch {
    return { response: null, sourceUrl, usedNetworkFallback: true };
  }
}

async function fetchFreshPlayerResponse(
  videoId: string,
  apiKey: string | undefined,
  fetchImpl: FetchText
): Promise<PlayerResponse | null> {
  if (!videoId || !apiKey) return null;
  try {
    const body = await fetchImpl(`https://www.youtube.com/youtubei/v1/player?key=${encodeURIComponent(apiKey)}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        videoId,
        context: {
          client: {
            clientName: "WEB",
            clientVersion: "2.20240625.01.00"
          }
        }
      })
    });
    return JSON.parse(body) as PlayerResponse;
  } catch {
    return null;
  }
}

function mergeTracks(primary: CaptionTrack[], secondary: CaptionTrack[]): CaptionTrack[] {
  const seen = new Set<string>();
  const merged: CaptionTrack[] = [];
  for (const track of [...primary, ...secondary]) {
    const key = `${track.languageCode}|${track.kind || ""}|${track.baseUrl}`;
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(track);
  }
  return merged;
}

async function loadFromTracks(
  tracks: CaptionTrack[],
  preferredLanguage: string | undefined,
  fetchImpl: FetchText
): Promise<{ chosen?: CaptionTrack; segments: TranscriptSegment[]; errors: string[] }> {
  const candidates = orderedTracks(tracks, preferredLanguage);
  const errors: string[] = [];
  for (const candidate of candidates) {
    try {
      return {
        chosen: candidate,
        segments: await loadCaptionSegments(candidate, fetchImpl),
        errors
      };
    } catch (error) {
      errors.push(
        `${candidate.languageCode}${candidate.isAutoGenerated ? " auto" : ""}: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }
  return { chosen: candidates[0], segments: [], errors };
}

/**
 * Top-level capture entry point. Reads the player response from the page,
 * resolves a caption track, fetches and parses it, and assembles a draft.
 * Throws a `TranscriptionError` (recoverable) when the page needs a reload.
 */
export async function captureTranscript(
  source: string | Document,
  fetchImpl: FetchText = defaultFetch,
  options: CaptureOptions = {}
): Promise<CaptureResult> {
  const { response, sourceUrl, apiKey, usedNetworkFallback } = await resolvePlayerResponse(source, fetchImpl);
  if (!response) {
    throw new TranscriptionError(
      usedNetworkFallback
        ? "YouTube's player data was not found in the page or fresh watch HTML. Open a standard YouTube watch URL, wait for the video to finish loading, then try again."
        : "YouTube's player data was not found on this page. Reload the video and try again.",
      true
    );
  }

  const status = response.playabilityStatus?.status;
  if (status && status !== "OK" && status !== "LIVE_STREAM_OFFLINE") {
    throw new TranscriptionError(
      `This video cannot be played (${response.playabilityStatus?.reason || status}).`,
      false
    );
  }

  const video = buildVideoMeta(response, sourceUrl);
  let tracks = normalizeCaptionTracks(
    response.captions?.playerCaptionsTracklistRenderer?.captionTracks
  );
  const warnings: string[] = [];
  let chosen: CaptionTrack | undefined;
  let segments: TranscriptSegment[] = [];

  if (!tracks.length) {
    warnings.push("This video has no caption tracks; no transcript is available.");
  } else {
    let result = await loadFromTracks(tracks, options.preferredLanguage, fetchImpl);
    chosen = result.chosen;
    segments = result.segments;
    let loadErrors = result.errors;

    if (!segments.length) {
      const freshResponse = await fetchFreshPlayerResponse(video.videoId, apiKey, fetchImpl);
      const freshTracks = normalizeCaptionTracks(
        freshResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks
      );
      if (freshTracks.length) {
        tracks = mergeTracks(tracks, freshTracks);
        result = await loadFromTracks(tracks, options.preferredLanguage, fetchImpl);
        chosen = result.chosen;
        segments = result.segments;
        loadErrors = [...loadErrors, ...result.errors];
      }
    }

    if (!segments.length) {
      warnings.push(
        `No caption track could be loaded. Tried ${tracks.length} track${
          tracks.length === 1 ? "" : "s"
        }: ${loadErrors.join(" | ")}`
      );
    }

    if (chosen?.isAutoGenerated) {
      warnings.push(
        `Transcript is auto-generated (${chosen.languageCode}); expect reduced accuracy.`
      );
    }
    if (segments.length && video.lengthSeconds > 0) {
      const expectedMs = video.lengthSeconds * 1000;
      const lastEnd = segments[segments.length - 1]!.endMs;
      if (lastEnd < expectedMs * 0.9) {
        warnings.push("Transcript appears truncated relative to the video duration.");
      }
    }
  }

  const chapters = parseChapters(video.shortDescription);
  const completeness = warnings.some((warning) => /truncat/i.test(warning))
    ? "possibly-truncated"
    : "complete";

  return {
    draft: {
      video,
      segments,
      chapters,
      captionTrack: chosen,
      completeness,
      warnings
    }
  };
}

async function defaultFetch(url: string, init: RequestInit = {}): Promise<string> {
  const response = await fetch(url, { credentials: "include", ...init });
  if (!response.ok) throw new Error(`Caption request failed (HTTP ${response.status}).`);
  return response.text();
}
