export type Completeness = "complete" | "possibly-truncated";

export interface TranscriptSegment {
  startMs: number;
  endMs: number;
  text: string;
}

export interface Chapter {
  title: string;
  startMs: number;
}

export interface VideoMeta {
  videoId: string;
  title: string;
  author: string;
  lengthSeconds: number;
  publishedAt?: string;
  shortDescription: string;
  sourceUrl: string;
}

export interface CaptionTrack {
  languageCode: string;
  kind?: string;
  name: string;
  baseUrl: string;
  vssId?: string;
  isAutoGenerated: boolean;
}

export interface TranscriptDraft {
  video: VideoMeta;
  segments: TranscriptSegment[];
  chapters: Chapter[];
  captionTrack?: CaptionTrack;
  completeness: Completeness;
  warnings: string[];
}

export interface TranscriptSnapshot {
  schemaVersion: 1;
  id?: string;
  videoId: string;
  title: string;
  author: string;
  sourceUrl: string;
  capturedAt: string;
  lengthSeconds: number;
  captionLanguage?: string;
  captionAutoGenerated?: boolean;
  chapters: Chapter[];
  segments: TranscriptSegment[];
  renderedMarkdown: string;
  plainText: string;
  srt: string;
  vtt: string;
  completeness: Completeness;
  warnings: string[];
}

export interface ArchiveListItem {
  id: string;
  videoId: string;
  title: string;
  author: string;
  capturedAt: string;
  captionAutoGenerated?: boolean;
  completeness: Completeness;
}
