import { captureTranscript, TranscriptionError } from "../core/transcript";
import { normalizeSnapshot, toCopyText, toMarkdown } from "../core/render";
import { downloadText, safeFilename } from "../core/download";
import { isWatchUrl } from "../core/permissions";
import {
  loadPreferences,
  renderFilenameTemplate,
  type LauncherPosition,
  type TubePreferences
} from "../core/preferences";
import type { TranscriptSnapshot } from "../core/types";
import { mountLauncher } from "../ui/launcher";
import { showOverlay, type OverlayAction } from "../ui/overlay";
import { showToast } from "../ui/toast";

declare global {
  interface Window {
    __tubeUtilitiesLoaded?: boolean;
  }
}

if (!window.__tubeUtilitiesLoaded) {
  window.__tubeUtilitiesLoaded = true;
  let currentSnapshot: TranscriptSnapshot | null = null;

  const capture = async () => {
    const preferences = await loadPreferences();
    const result = await captureTranscript(document, undefined, {
      preferredLanguage: preferences.preferredLanguage || undefined
    });
    currentSnapshot = result.draft.segments.length || result.draft.warnings.length
      ? normalizeSnapshot(result.draft)
      : null;
    return currentSnapshot;
  };

  const filenameFor = (snapshot: TranscriptSnapshot, extension: string, preferences: TubePreferences) => {
    return safeFilename(
      renderFilenameTemplate(preferences.filenameTemplate, {
        title: snapshot.title,
        author: snapshot.author,
        date: snapshot.capturedAt.slice(0, 10),
        videoId: snapshot.videoId
      }),
      extension
    );
  };

  const draftFromSnapshot = (snapshot: TranscriptSnapshot) => ({
    video: {
      videoId: snapshot.videoId,
      title: snapshot.title,
      author: snapshot.author,
      lengthSeconds: snapshot.lengthSeconds,
      shortDescription: "",
      sourceUrl: snapshot.sourceUrl
    },
    segments: snapshot.segments,
    chapters: snapshot.chapters,
    captionTrack: snapshot.captionLanguage
      ? {
          languageCode: snapshot.captionLanguage,
          name: snapshot.captionLanguage,
          baseUrl: "",
          isAutoGenerated: snapshot.captionAutoGenerated === true
        }
      : undefined,
    completeness: snapshot.completeness,
    warnings: snapshot.warnings
  });

  const act = async (action: OverlayAction) => {
    try {
      const snapshot = currentSnapshot || await capture();
      if (!snapshot || !snapshot.segments.length) {
        showToast(
          snapshot?.warnings[0] || "No transcript segments were detected on this page.",
          "error"
        );
        return;
      }
      const preferences = await loadPreferences();
      const draft = draftFromSnapshot(snapshot);
      if (action === "markdown") {
        downloadText(
          filenameFor(snapshot, "md", preferences),
          toMarkdown(draft, { includeTimestamps: preferences.includeTimestamps }),
          "text/markdown"
        );
        showToast("Markdown download started.");
      } else if (action === "plain") {
        downloadText(filenameFor(snapshot, "txt", preferences), snapshot.plainText, "text/plain");
        showToast("Plain text download started.");
      } else if (action === "srt") {
        downloadText(filenameFor(snapshot, "srt", preferences), snapshot.srt, "application/x-subrip");
        showToast("SubRip download started.");
      } else if (action === "vtt") {
        downloadText(filenameFor(snapshot, "vtt", preferences), snapshot.vtt, "text/vtt");
        showToast("WebVTT download started.");
      } else if (action === "copy") {
        await navigator.clipboard.writeText(toCopyText(draft));
        showToast("Transcript copied.");
      } else if (action === "archive") {
        const response = await chrome.runtime.sendMessage({ type: "ARCHIVE_SAVE", snapshot });
        if (!response?.ok) throw new Error(response?.error || "Archive save failed.");
        showToast("Transcript saved to the local archive.");
      }
    } catch (error) {
      showToast(error instanceof Error ? error.message : "The requested action failed.", "error");
    }
  };

  const open = async () => {
    try {
      await capture();
    } catch (error) {
      if (error instanceof TranscriptionError) {
        showToast(error.message, "error");
        return;
      }
      throw error;
    }
    showOverlay(currentSnapshot, act);
  };

  const mountConfiguredLauncher = async () => {
    if (!isWatchUrl(location.href)) {
      document.querySelector("[data-tube-launcher]")?.remove();
      return;
    }
    const { launcherEnabled, launcherPosition } = await loadPreferences();
    document.querySelector("[data-tube-launcher]")?.remove();
    if (launcherEnabled) mountLauncher(open, launcherPosition as LauncherPosition);
  };

  void mountConfiguredLauncher();

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message.type === "SHOW_OVERLAY") {
      open()
        .then(() => sendResponse({ ok: true }))
        .catch((error) => {
          showToast(error instanceof Error ? error.message : "Capture failed.", "error");
          sendResponse({ ok: false });
        });
      return true;
    }
    if (message.type === "PING") sendResponse({ ok: true });
  });

  // YouTube is a single-page app: watch for client-side navigation between videos.
  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      currentSnapshot = null;
      void mountConfiguredLauncher();
    }
  });
  observer.observe(document.documentElement, { childList: true, subtree: true });
}
