import { isWatchUrl } from "../core/permissions";
import type { ArchiveListItem } from "../core/types";

const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;

async function loadStatus(): Promise<void> {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const url = tab?.url || "";
  const watch = isWatchUrl(url);
  $("#siteName").textContent = watch ? "YouTube watch page" : "Open a YouTube video";
  $("#siteStatus").textContent = watch
    ? "Ready to capture this video's transcript."
    : "Tube Utilities works on YouTube watch pages. Open one to begin.";
  ($("#captureButton") as HTMLButtonElement).disabled = !watch;
  $("#captureButton").textContent = watch ? "Capture transcript" : "No video open";
}

async function loadArchive(): Promise<void> {
  const response = await chrome.runtime.sendMessage({
    type: "ARCHIVE_LIST",
    query: ($("#searchInput") as HTMLInputElement).value
  });
  const list = $("#archiveList");
  list.replaceChildren();
  for (const item of response.items as ArchiveListItem[]) {
    const button = document.createElement("button");
    button.className = "archive-item";
    button.innerHTML = `<span><strong></strong><small></small></span><em></em>`;
    button.querySelector("strong")!.textContent = item.title;
    button.querySelector("small")!.textContent =
      `${item.author} · ${new Date(item.capturedAt).toLocaleString()}`;
    button.querySelector("em")!.textContent = item.captionAutoGenerated ? "auto" : "captions";
    button.addEventListener("click", () =>
      chrome.tabs.create({ url: chrome.runtime.getURL(`archive.html?id=${item.id}`) })
    );
    list.append(button);
  }
  if (!list.childElementCount) list.textContent = "No archived transcripts.";
}

document.addEventListener("DOMContentLoaded", async () => {
  $("#captureButton").addEventListener("click", async () => {
    const result = await chrome.runtime.sendMessage({ type: "START_CAPTURE" });
    if (result.ok) window.close();
    else $("#siteStatus").textContent = result.error;
  });
  $("#settingsButton").addEventListener("click", () => chrome.runtime.openOptionsPage());
  $("#searchInput").addEventListener("input", loadArchive);
  await Promise.all([loadStatus(), loadArchive()]);
});
