import { describe, expect, it } from "vitest";
import { normalizeSnapshot, toPlainText, toSrt, toVtt } from "../src/core/render";
import type { TranscriptDraft } from "../src/core/types";

const draft: TranscriptDraft = {
  video: {
    videoId: "abc123",
    title: "Example Video",
    author: "Example Channel",
    lengthSeconds: 5,
    shortDescription: "0:00 Intro\n0:03 Wrap",
    sourceUrl: "https://www.youtube.com/watch?v=abc123"
  },
  captionTrack: {
    languageCode: "en",
    name: "English",
    baseUrl: "https://example.test/caption",
    isAutoGenerated: false
  },
  chapters: [{ title: "Intro", startMs: 0 }],
  segments: [
    { startMs: 0, endMs: 1200, text: "Hello world." },
    { startMs: 3400, endMs: 4600, text: "Second line." }
  ],
  completeness: "complete",
  warnings: []
};

describe("renderers", () => {
  it("renders plain text with paragraph breaks", () => {
    expect(toPlainText(draft)).toBe("Hello world.\n\nSecond line.");
  });

  it("renders subtitle formats", () => {
    expect(toSrt(draft)).toContain("00:00:00,000 --> 00:00:01,200");
    expect(toVtt(draft)).toContain("WEBVTT");
  });

  it("normalizes archive snapshots", () => {
    const snapshot = normalizeSnapshot(draft, "2026-06-25T00:00:00.000Z");
    expect(snapshot.videoId).toBe("abc123");
    expect(snapshot.renderedMarkdown).toContain("# Example Video");
  });
});
