import { afterEach, describe, expect, it, vi } from "vitest";
import { captureTranscript, parseTimedTextXml, readPlayerResponse } from "../src/core/transcript";

function playerHtml(
  captionUrl = "https://www.youtube.com/api/timedtext?v=abc123",
  extraTracks: unknown[] = []
): string {
  const response = {
    playabilityStatus: { status: "OK" },
    videoDetails: {
      videoId: "abc123",
      title: "Fallback Video",
      author: "Fallback Channel",
      lengthSeconds: "4",
      shortDescription: "0:00 Intro\n0:02 Point"
    },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [{
          languageCode: "en",
          name: { simpleText: "English" },
          baseUrl: captionUrl,
          vssId: ".en"
        }, ...extraTracks]
      }
    }
  };
  return `<html><script>ytcfg.set({"INNERTUBE_API_KEY":"test-api-key"}); var ytInitialPlayerResponse = ${JSON.stringify(response)};</script></html>`;
}

describe("transcript capture", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("parses embedded YouTube player data", () => {
    const response = readPlayerResponse(playerHtml());
    expect(response?.videoDetails?.videoId).toBe("abc123");
    expect(response?.captions?.playerCaptionsTracklistRenderer?.captionTracks?.[0]?.languageCode).toBe("en");
  });

  it("falls back to fresh watch HTML when SPA DOM no longer contains player data", async () => {
    vi.stubGlobal("location", { href: "https://www.youtube.com/watch?v=abc123" });
    const doc = { documentElement: { outerHTML: "<html><body>SPA shell</body></html>" } } as Document;
    const fetchImpl = vi.fn(async (url: string) => {
      if (url.includes("/watch")) return playerHtml("https://www.youtube.com/api/timedtext?v=abc123");
      return JSON.stringify({
        events: [
          { tStartMs: 0, dDurationMs: 900, segs: [{ utf8: "Hello" }] },
          { tStartMs: 1000, dDurationMs: 900, segs: [{ utf8: "world" }] }
        ]
      });
    });

    const result = await captureTranscript(doc, fetchImpl);

    expect(fetchImpl).toHaveBeenCalledWith("https://www.youtube.com/watch?v=abc123");
    expect(result.draft.video.title).toBe("Fallback Video");
    expect(result.draft.segments.map((segment) => segment.text)).toEqual(["Hello", "world"]);
  });

  it("parses YouTube timed-text XML captions", () => {
    const segments = parseTimedTextXml(
      '<transcript><text start="0" dur="1.2">Hello &amp; welcome</text><text start="1.5" dur="0.8">Second line</text></transcript>'
    );

    expect(segments).toEqual([
      { startMs: 0, endMs: 1200, text: "Hello & welcome" },
      { startMs: 1500, endMs: 2300, text: "Second line" }
    ]);
  });

  it("falls back to XML captions when JSON3 is empty", async () => {
    vi.stubGlobal("location", { href: "https://www.youtube.com/watch?v=abc123" });
    const fetchImpl = vi.fn(async (url: string) => {
      if (url.includes("fmt=json3")) return "";
      return '<transcript><text start="0" dur="1">XML fallback works</text></transcript>';
    });

    const result = await captureTranscript(playerHtml(), fetchImpl);

    expect(result.draft.segments.map((segment) => segment.text)).toEqual(["XML fallback works"]);
    expect(fetchImpl.mock.calls.some(([url]) => !String(url).includes("fmt=json3"))).toBe(true);
  });

  it("tries another caption track when the preferred track is empty", async () => {
    vi.stubGlobal("location", { href: "https://www.youtube.com/watch?v=abc123" });
    const html = playerHtml("https://www.youtube.com/api/timedtext?v=abc123&lang=en", [{
      languageCode: "en",
      kind: "asr",
      name: { simpleText: "English auto" },
      baseUrl: "https://www.youtube.com/api/timedtext?v=abc123&lang=en-auto",
      vssId: "a.en"
    }]);
    const fetchImpl = vi.fn(async (url: string) => {
      if (url.includes("en-auto")) {
        return JSON.stringify({
          events: [{ tStartMs: 0, dDurationMs: 1000, segs: [{ utf8: "Auto fallback works" }] }]
        });
      }
      return "";
    });

    const result = await captureTranscript(html, fetchImpl, { preferredLanguage: "en" });

    expect(result.draft.captionTrack?.isAutoGenerated).toBe(true);
    expect(result.draft.segments.map((segment) => segment.text)).toEqual(["Auto fallback works"]);
  });

  it("refreshes player metadata when embedded caption URLs are stale", async () => {
    vi.stubGlobal("location", { href: "https://www.youtube.com/watch?v=abc123" });
    const fetchImpl = vi.fn(async (url: string, init?: RequestInit) => {
      if (url.includes("/youtubei/v1/player")) {
        expect(init?.method).toBe("POST");
        return JSON.stringify({
          playabilityStatus: { status: "OK" },
          videoDetails: {
            videoId: "abc123",
            title: "Fresh Video",
            author: "Fresh Channel",
            lengthSeconds: "4",
            shortDescription: ""
          },
          captions: {
            playerCaptionsTracklistRenderer: {
              captionTracks: [{
                languageCode: "en",
                name: { simpleText: "English fresh" },
                baseUrl: "https://www.youtube.com/api/timedtext?v=abc123&lang=fresh",
                vssId: ".en"
              }]
            }
          }
        });
      }
      if (url.includes("lang=fresh")) {
        return JSON.stringify({
          events: [{ tStartMs: 0, dDurationMs: 1000, segs: [{ utf8: "Fresh metadata works" }] }]
        });
      }
      return "";
    });

    const result = await captureTranscript(
      playerHtml("https://www.youtube.com/api/timedtext?v=abc123&lang=stale"),
      fetchImpl
    );

    expect(fetchImpl.mock.calls.some(([url]) => String(url).includes("/youtubei/v1/player"))).toBe(true);
    expect(result.draft.segments.map((segment) => segment.text)).toEqual(["Fresh metadata works"]);
  });
});
